### ISSUE TITLE
Unable to launch broser

### ISSUE THREAD

**Issue by pradeepst13** [pradeepst13/selenium_training#1]
package openbrowser;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Chromebrowser {

	public static void main(String[] args) {

// launch chromebrwoser
		
		System.setProperty("webdriver.Chrome.driver", "C:\\Selenium New\\Driver\\chromedriver.exe");
		WebDriver driver= new ChromeDriver();

	}

}

Exception  : 

Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:754)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:124)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:339)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at openbrowser.Chromebrowser.main(Chromebrowser.java:13)

**Comment by pradeepst13** [comment]
Issue Solved. Hence closed the comment
